// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

 `timescale 1ns/1ps


`define AUTOTB_DUT      state_observer
`define AUTOTB_DUT_INST AESL_inst_state_observer
`define AUTOTB_TOP      apatb_state_observer_top
`define AUTOTB_LAT_RESULT_FILE "state_observer.result.lat.rb"
`define AUTOTB_PER_RESULT_TRANS_FILE "state_observer.performance.result.transaction.xml"
`define AUTOTB_TOP_INST AESL_inst_apatb_state_observer_top
`define AUTOTB_MAX_ALLOW_LATENCY  15000000
`define AUTOTB_CLOCK_PERIOD_DIV2 5.00

`define AESL_DEPTH_x1_V 1
`define AESL_DEPTH_x2_V 1
`define AESL_DEPTH_u_1_V 1
`define AESL_DEPTH_u_2_V 1
`define AESL_DEPTH_x_obs_old_0_V 1
`define AESL_DEPTH_x_obs_old_1_V 1
`define AESL_DEPTH_x_obs_old_2_V 1
`define AESL_DEPTH_x_obs_old_3_V 1
`define AESL_DEPTH_x_obs_old_4_V 1
`define AESL_DEPTH_x_obs_old_5_V 1
`define AESL_DEPTH_x_obs_0_o_V 1
`define AESL_DEPTH_x_obs_1_o_V 1
`define AESL_DEPTH_x_obs_2_o_V 1
`define AESL_DEPTH_x_obs_3_o_V 1
`define AESL_DEPTH_x_obs_4_o_V 1
`define AESL_DEPTH_x_obs_5_o_V 1
`define AUTOTB_TVIN_x1_V  "../tv/cdatafile/c.state_observer.autotvin_x1_V.dat"
`define AUTOTB_TVIN_x2_V  "../tv/cdatafile/c.state_observer.autotvin_x2_V.dat"
`define AUTOTB_TVIN_u_1_V  "../tv/cdatafile/c.state_observer.autotvin_u_1_V.dat"
`define AUTOTB_TVIN_u_2_V  "../tv/cdatafile/c.state_observer.autotvin_u_2_V.dat"
`define AUTOTB_TVIN_x_obs_old_0_V  "../tv/cdatafile/c.state_observer.autotvin_x_obs_old_0_V.dat"
`define AUTOTB_TVIN_x_obs_old_1_V  "../tv/cdatafile/c.state_observer.autotvin_x_obs_old_1_V.dat"
`define AUTOTB_TVIN_x_obs_old_2_V  "../tv/cdatafile/c.state_observer.autotvin_x_obs_old_2_V.dat"
`define AUTOTB_TVIN_x_obs_old_3_V  "../tv/cdatafile/c.state_observer.autotvin_x_obs_old_3_V.dat"
`define AUTOTB_TVIN_x_obs_old_4_V  "../tv/cdatafile/c.state_observer.autotvin_x_obs_old_4_V.dat"
`define AUTOTB_TVIN_x_obs_old_5_V  "../tv/cdatafile/c.state_observer.autotvin_x_obs_old_5_V.dat"
`define AUTOTB_TVIN_x1_V_out_wrapc  "../tv/rtldatafile/rtl.state_observer.autotvin_x1_V.dat"
`define AUTOTB_TVIN_x2_V_out_wrapc  "../tv/rtldatafile/rtl.state_observer.autotvin_x2_V.dat"
`define AUTOTB_TVIN_u_1_V_out_wrapc  "../tv/rtldatafile/rtl.state_observer.autotvin_u_1_V.dat"
`define AUTOTB_TVIN_u_2_V_out_wrapc  "../tv/rtldatafile/rtl.state_observer.autotvin_u_2_V.dat"
`define AUTOTB_TVIN_x_obs_old_0_V_out_wrapc  "../tv/rtldatafile/rtl.state_observer.autotvin_x_obs_old_0_V.dat"
`define AUTOTB_TVIN_x_obs_old_1_V_out_wrapc  "../tv/rtldatafile/rtl.state_observer.autotvin_x_obs_old_1_V.dat"
`define AUTOTB_TVIN_x_obs_old_2_V_out_wrapc  "../tv/rtldatafile/rtl.state_observer.autotvin_x_obs_old_2_V.dat"
`define AUTOTB_TVIN_x_obs_old_3_V_out_wrapc  "../tv/rtldatafile/rtl.state_observer.autotvin_x_obs_old_3_V.dat"
`define AUTOTB_TVIN_x_obs_old_4_V_out_wrapc  "../tv/rtldatafile/rtl.state_observer.autotvin_x_obs_old_4_V.dat"
`define AUTOTB_TVIN_x_obs_old_5_V_out_wrapc  "../tv/rtldatafile/rtl.state_observer.autotvin_x_obs_old_5_V.dat"
`define AUTOTB_TVOUT_x_obs_0_o_V  "../tv/cdatafile/c.state_observer.autotvout_x_obs_0_o_V.dat"
`define AUTOTB_TVOUT_x_obs_1_o_V  "../tv/cdatafile/c.state_observer.autotvout_x_obs_1_o_V.dat"
`define AUTOTB_TVOUT_x_obs_2_o_V  "../tv/cdatafile/c.state_observer.autotvout_x_obs_2_o_V.dat"
`define AUTOTB_TVOUT_x_obs_3_o_V  "../tv/cdatafile/c.state_observer.autotvout_x_obs_3_o_V.dat"
`define AUTOTB_TVOUT_x_obs_4_o_V  "../tv/cdatafile/c.state_observer.autotvout_x_obs_4_o_V.dat"
`define AUTOTB_TVOUT_x_obs_5_o_V  "../tv/cdatafile/c.state_observer.autotvout_x_obs_5_o_V.dat"
`define AUTOTB_TVOUT_x_obs_0_o_V_out_wrapc  "../tv/rtldatafile/rtl.state_observer.autotvout_x_obs_0_o_V.dat"
`define AUTOTB_TVOUT_x_obs_1_o_V_out_wrapc  "../tv/rtldatafile/rtl.state_observer.autotvout_x_obs_1_o_V.dat"
`define AUTOTB_TVOUT_x_obs_2_o_V_out_wrapc  "../tv/rtldatafile/rtl.state_observer.autotvout_x_obs_2_o_V.dat"
`define AUTOTB_TVOUT_x_obs_3_o_V_out_wrapc  "../tv/rtldatafile/rtl.state_observer.autotvout_x_obs_3_o_V.dat"
`define AUTOTB_TVOUT_x_obs_4_o_V_out_wrapc  "../tv/rtldatafile/rtl.state_observer.autotvout_x_obs_4_o_V.dat"
`define AUTOTB_TVOUT_x_obs_5_o_V_out_wrapc  "../tv/rtldatafile/rtl.state_observer.autotvout_x_obs_5_o_V.dat"
module `AUTOTB_TOP;

parameter AUTOTB_TRANSACTION_NUM = 1;
parameter PROGRESS_TIMEOUT = 10000000;
parameter LATENCY_ESTIMATION = 148;
parameter LENGTH_x1_V = 1;
parameter LENGTH_x2_V = 1;
parameter LENGTH_u_1_V = 1;
parameter LENGTH_u_2_V = 1;
parameter LENGTH_x_obs_old_0_V = 1;
parameter LENGTH_x_obs_old_1_V = 1;
parameter LENGTH_x_obs_old_2_V = 1;
parameter LENGTH_x_obs_old_3_V = 1;
parameter LENGTH_x_obs_old_4_V = 1;
parameter LENGTH_x_obs_old_5_V = 1;
parameter LENGTH_x_obs_0_o_V = 1;
parameter LENGTH_x_obs_1_o_V = 1;
parameter LENGTH_x_obs_2_o_V = 1;
parameter LENGTH_x_obs_3_o_V = 1;
parameter LENGTH_x_obs_4_o_V = 1;
parameter LENGTH_x_obs_5_o_V = 1;

task read_token;
    input integer fp;
    output reg [167 : 0] token;
    integer ret;
    begin
        token = "";
        ret = 0;
        ret = $fscanf(fp,"%s",token);
    end
endtask

reg AESL_clock;
reg rst;
reg start;
reg ce;
reg tb_continue;
wire AESL_start;
wire AESL_reset;
wire AESL_ce;
wire AESL_ready;
wire AESL_idle;
wire AESL_continue;
wire AESL_done;
reg AESL_done_delay = 0;
reg AESL_done_delay2 = 0;
reg AESL_ready_delay = 0;
wire ready;
wire ready_wire;
wire ap_start;
wire ap_done;
wire ap_idle;
wire ap_ready;
wire [15 : 0] x1_V;
wire [15 : 0] x2_V;
wire [15 : 0] u_1_V;
wire [15 : 0] u_2_V;
wire [15 : 0] x_obs_old_0_V;
wire [15 : 0] x_obs_old_1_V;
wire [15 : 0] x_obs_old_2_V;
wire [15 : 0] x_obs_old_3_V;
wire [15 : 0] x_obs_old_4_V;
wire [15 : 0] x_obs_old_5_V;
wire [15 : 0] x_obs_0_o_V;
wire  x_obs_0_o_V_ap_vld;
wire [15 : 0] x_obs_1_o_V;
wire  x_obs_1_o_V_ap_vld;
wire [15 : 0] x_obs_2_o_V;
wire  x_obs_2_o_V_ap_vld;
wire [15 : 0] x_obs_3_o_V;
wire  x_obs_3_o_V_ap_vld;
wire [15 : 0] x_obs_4_o_V;
wire  x_obs_4_o_V_ap_vld;
wire [15 : 0] x_obs_5_o_V;
wire  x_obs_5_o_V_ap_vld;
integer done_cnt = 0;
integer AESL_ready_cnt = 0;
integer ready_cnt = 0;
reg ready_initial;
reg ready_initial_n;
reg ready_last_n;
reg ready_delay_last_n;
reg done_delay_last_n;
reg interface_done = 0;

wire ap_clk;
wire ap_rst;
wire ap_rst_n;

`AUTOTB_DUT `AUTOTB_DUT_INST(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .ap_ready(ap_ready),
    .x1_V(x1_V),
    .x2_V(x2_V),
    .u_1_V(u_1_V),
    .u_2_V(u_2_V),
    .x_obs_old_0_V(x_obs_old_0_V),
    .x_obs_old_1_V(x_obs_old_1_V),
    .x_obs_old_2_V(x_obs_old_2_V),
    .x_obs_old_3_V(x_obs_old_3_V),
    .x_obs_old_4_V(x_obs_old_4_V),
    .x_obs_old_5_V(x_obs_old_5_V),
    .x_obs_0_o_V(x_obs_0_o_V),
    .x_obs_0_o_V_ap_vld(x_obs_0_o_V_ap_vld),
    .x_obs_1_o_V(x_obs_1_o_V),
    .x_obs_1_o_V_ap_vld(x_obs_1_o_V_ap_vld),
    .x_obs_2_o_V(x_obs_2_o_V),
    .x_obs_2_o_V_ap_vld(x_obs_2_o_V_ap_vld),
    .x_obs_3_o_V(x_obs_3_o_V),
    .x_obs_3_o_V_ap_vld(x_obs_3_o_V_ap_vld),
    .x_obs_4_o_V(x_obs_4_o_V),
    .x_obs_4_o_V_ap_vld(x_obs_4_o_V_ap_vld),
    .x_obs_5_o_V(x_obs_5_o_V),
    .x_obs_5_o_V_ap_vld(x_obs_5_o_V_ap_vld));

// Assignment for control signal
assign ap_clk = AESL_clock;
assign ap_rst = AESL_reset;
assign ap_rst_n = ~AESL_reset;
assign AESL_reset = rst;
assign ap_start = AESL_start;
assign AESL_start = start;
assign AESL_done = ap_done;
assign AESL_idle = ap_idle;
assign AESL_ready = ap_ready;
assign AESL_ce = ce;
assign AESL_continue = tb_continue;
    always @(posedge AESL_clock) begin
        if (AESL_reset) begin
        end else begin
            if (AESL_done !== 1 && AESL_done !== 0) begin
                $display("ERROR: Control signal AESL_done is invalid!");
                $finish;
            end
        end
    end
    always @(posedge AESL_clock) begin
        if (AESL_reset) begin
        end else begin
            if (AESL_ready !== 1 && AESL_ready !== 0) begin
                $display("ERROR: Control signal AESL_ready is invalid!");
                $finish;
            end
        end
    end
// The signal of port x1_V
reg [15: 0] AESL_REG_x1_V = 0;
assign x1_V = AESL_REG_x1_V;
initial begin : read_file_process_x1_V
    integer fp;
    integer err;
    integer ret;
    integer proc_rand;
    reg [167  : 0] token;
    integer i;
    reg transaction_finish;
    integer transaction_idx;
    transaction_idx = 0;
    wait(AESL_reset === 0);
    fp = $fopen(`AUTOTB_TVIN_x1_V,"r");
    if(fp == 0) begin       // Failed to open file
        $display("Failed to open file \"%s\"!", `AUTOTB_TVIN_x1_V);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    read_token(fp, token);
    if (token != "[[[runtime]]]") begin
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    read_token(fp, token);
    while (token != "[[[/runtime]]]") begin
        if (token != "[[transaction]]") begin
            $display("ERROR: Simulation using HLS TB failed.");
              $finish;
        end
        read_token(fp, token);  // skip transaction number
          read_token(fp, token);
            # 0.2;
            while(ready_wire !== 1) begin
                @(posedge AESL_clock);
                # 0.2;
            end
        if(token != "[[/transaction]]") begin
            ret = $sscanf(token, "0x%x", AESL_REG_x1_V);
              if (ret != 1) begin
                  $display("Failed to parse token!");
                $display("ERROR: Simulation using HLS TB failed.");
                  $finish;
              end
            @(posedge AESL_clock);
              read_token(fp, token);
        end
          read_token(fp, token);
    end
    $fclose(fp);
end


// The signal of port x2_V
reg [15: 0] AESL_REG_x2_V = 0;
assign x2_V = AESL_REG_x2_V;
initial begin : read_file_process_x2_V
    integer fp;
    integer err;
    integer ret;
    integer proc_rand;
    reg [167  : 0] token;
    integer i;
    reg transaction_finish;
    integer transaction_idx;
    transaction_idx = 0;
    wait(AESL_reset === 0);
    fp = $fopen(`AUTOTB_TVIN_x2_V,"r");
    if(fp == 0) begin       // Failed to open file
        $display("Failed to open file \"%s\"!", `AUTOTB_TVIN_x2_V);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    read_token(fp, token);
    if (token != "[[[runtime]]]") begin
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    read_token(fp, token);
    while (token != "[[[/runtime]]]") begin
        if (token != "[[transaction]]") begin
            $display("ERROR: Simulation using HLS TB failed.");
              $finish;
        end
        read_token(fp, token);  // skip transaction number
          read_token(fp, token);
            # 0.2;
            while(ready_wire !== 1) begin
                @(posedge AESL_clock);
                # 0.2;
            end
        if(token != "[[/transaction]]") begin
            ret = $sscanf(token, "0x%x", AESL_REG_x2_V);
              if (ret != 1) begin
                  $display("Failed to parse token!");
                $display("ERROR: Simulation using HLS TB failed.");
                  $finish;
              end
            @(posedge AESL_clock);
              read_token(fp, token);
        end
          read_token(fp, token);
    end
    $fclose(fp);
end


// The signal of port u_1_V
reg [15: 0] AESL_REG_u_1_V = 0;
assign u_1_V = AESL_REG_u_1_V;
initial begin : read_file_process_u_1_V
    integer fp;
    integer err;
    integer ret;
    integer proc_rand;
    reg [167  : 0] token;
    integer i;
    reg transaction_finish;
    integer transaction_idx;
    transaction_idx = 0;
    wait(AESL_reset === 0);
    fp = $fopen(`AUTOTB_TVIN_u_1_V,"r");
    if(fp == 0) begin       // Failed to open file
        $display("Failed to open file \"%s\"!", `AUTOTB_TVIN_u_1_V);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    read_token(fp, token);
    if (token != "[[[runtime]]]") begin
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    read_token(fp, token);
    while (token != "[[[/runtime]]]") begin
        if (token != "[[transaction]]") begin
            $display("ERROR: Simulation using HLS TB failed.");
              $finish;
        end
        read_token(fp, token);  // skip transaction number
          read_token(fp, token);
            # 0.2;
            while(ready_wire !== 1) begin
                @(posedge AESL_clock);
                # 0.2;
            end
        if(token != "[[/transaction]]") begin
            ret = $sscanf(token, "0x%x", AESL_REG_u_1_V);
              if (ret != 1) begin
                  $display("Failed to parse token!");
                $display("ERROR: Simulation using HLS TB failed.");
                  $finish;
              end
            @(posedge AESL_clock);
              read_token(fp, token);
        end
          read_token(fp, token);
    end
    $fclose(fp);
end


// The signal of port u_2_V
reg [15: 0] AESL_REG_u_2_V = 0;
assign u_2_V = AESL_REG_u_2_V;
initial begin : read_file_process_u_2_V
    integer fp;
    integer err;
    integer ret;
    integer proc_rand;
    reg [167  : 0] token;
    integer i;
    reg transaction_finish;
    integer transaction_idx;
    transaction_idx = 0;
    wait(AESL_reset === 0);
    fp = $fopen(`AUTOTB_TVIN_u_2_V,"r");
    if(fp == 0) begin       // Failed to open file
        $display("Failed to open file \"%s\"!", `AUTOTB_TVIN_u_2_V);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    read_token(fp, token);
    if (token != "[[[runtime]]]") begin
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    read_token(fp, token);
    while (token != "[[[/runtime]]]") begin
        if (token != "[[transaction]]") begin
            $display("ERROR: Simulation using HLS TB failed.");
              $finish;
        end
        read_token(fp, token);  // skip transaction number
          read_token(fp, token);
            # 0.2;
            while(ready_wire !== 1) begin
                @(posedge AESL_clock);
                # 0.2;
            end
        if(token != "[[/transaction]]") begin
            ret = $sscanf(token, "0x%x", AESL_REG_u_2_V);
              if (ret != 1) begin
                  $display("Failed to parse token!");
                $display("ERROR: Simulation using HLS TB failed.");
                  $finish;
              end
            @(posedge AESL_clock);
              read_token(fp, token);
        end
          read_token(fp, token);
    end
    $fclose(fp);
end


// The signal of port x_obs_old_0_V
reg [15: 0] AESL_REG_x_obs_old_0_V = 0;
assign x_obs_old_0_V = AESL_REG_x_obs_old_0_V;
initial begin : read_file_process_x_obs_old_0_V
    integer fp;
    integer err;
    integer ret;
    integer proc_rand;
    reg [167  : 0] token;
    integer i;
    reg transaction_finish;
    integer transaction_idx;
    transaction_idx = 0;
    wait(AESL_reset === 0);
    fp = $fopen(`AUTOTB_TVIN_x_obs_old_0_V,"r");
    if(fp == 0) begin       // Failed to open file
        $display("Failed to open file \"%s\"!", `AUTOTB_TVIN_x_obs_old_0_V);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    read_token(fp, token);
    if (token != "[[[runtime]]]") begin
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    read_token(fp, token);
    while (token != "[[[/runtime]]]") begin
        if (token != "[[transaction]]") begin
            $display("ERROR: Simulation using HLS TB failed.");
              $finish;
        end
        read_token(fp, token);  // skip transaction number
          read_token(fp, token);
            # 0.2;
            while(ready_wire !== 1) begin
                @(posedge AESL_clock);
                # 0.2;
            end
        if(token != "[[/transaction]]") begin
            ret = $sscanf(token, "0x%x", AESL_REG_x_obs_old_0_V);
              if (ret != 1) begin
                  $display("Failed to parse token!");
                $display("ERROR: Simulation using HLS TB failed.");
                  $finish;
              end
            @(posedge AESL_clock);
              read_token(fp, token);
        end
          read_token(fp, token);
    end
    $fclose(fp);
end


// The signal of port x_obs_old_1_V
reg [15: 0] AESL_REG_x_obs_old_1_V = 0;
assign x_obs_old_1_V = AESL_REG_x_obs_old_1_V;
initial begin : read_file_process_x_obs_old_1_V
    integer fp;
    integer err;
    integer ret;
    integer proc_rand;
    reg [167  : 0] token;
    integer i;
    reg transaction_finish;
    integer transaction_idx;
    transaction_idx = 0;
    wait(AESL_reset === 0);
    fp = $fopen(`AUTOTB_TVIN_x_obs_old_1_V,"r");
    if(fp == 0) begin       // Failed to open file
        $display("Failed to open file \"%s\"!", `AUTOTB_TVIN_x_obs_old_1_V);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    read_token(fp, token);
    if (token != "[[[runtime]]]") begin
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    read_token(fp, token);
    while (token != "[[[/runtime]]]") begin
        if (token != "[[transaction]]") begin
            $display("ERROR: Simulation using HLS TB failed.");
              $finish;
        end
        read_token(fp, token);  // skip transaction number
          read_token(fp, token);
            # 0.2;
            while(ready_wire !== 1) begin
                @(posedge AESL_clock);
                # 0.2;
            end
        if(token != "[[/transaction]]") begin
            ret = $sscanf(token, "0x%x", AESL_REG_x_obs_old_1_V);
              if (ret != 1) begin
                  $display("Failed to parse token!");
                $display("ERROR: Simulation using HLS TB failed.");
                  $finish;
              end
            @(posedge AESL_clock);
              read_token(fp, token);
        end
          read_token(fp, token);
    end
    $fclose(fp);
end


// The signal of port x_obs_old_2_V
reg [15: 0] AESL_REG_x_obs_old_2_V = 0;
assign x_obs_old_2_V = AESL_REG_x_obs_old_2_V;
initial begin : read_file_process_x_obs_old_2_V
    integer fp;
    integer err;
    integer ret;
    integer proc_rand;
    reg [167  : 0] token;
    integer i;
    reg transaction_finish;
    integer transaction_idx;
    transaction_idx = 0;
    wait(AESL_reset === 0);
    fp = $fopen(`AUTOTB_TVIN_x_obs_old_2_V,"r");
    if(fp == 0) begin       // Failed to open file
        $display("Failed to open file \"%s\"!", `AUTOTB_TVIN_x_obs_old_2_V);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    read_token(fp, token);
    if (token != "[[[runtime]]]") begin
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    read_token(fp, token);
    while (token != "[[[/runtime]]]") begin
        if (token != "[[transaction]]") begin
            $display("ERROR: Simulation using HLS TB failed.");
              $finish;
        end
        read_token(fp, token);  // skip transaction number
          read_token(fp, token);
            # 0.2;
            while(ready_wire !== 1) begin
                @(posedge AESL_clock);
                # 0.2;
            end
        if(token != "[[/transaction]]") begin
            ret = $sscanf(token, "0x%x", AESL_REG_x_obs_old_2_V);
              if (ret != 1) begin
                  $display("Failed to parse token!");
                $display("ERROR: Simulation using HLS TB failed.");
                  $finish;
              end
            @(posedge AESL_clock);
              read_token(fp, token);
        end
          read_token(fp, token);
    end
    $fclose(fp);
end


// The signal of port x_obs_old_3_V
reg [15: 0] AESL_REG_x_obs_old_3_V = 0;
assign x_obs_old_3_V = AESL_REG_x_obs_old_3_V;
initial begin : read_file_process_x_obs_old_3_V
    integer fp;
    integer err;
    integer ret;
    integer proc_rand;
    reg [167  : 0] token;
    integer i;
    reg transaction_finish;
    integer transaction_idx;
    transaction_idx = 0;
    wait(AESL_reset === 0);
    fp = $fopen(`AUTOTB_TVIN_x_obs_old_3_V,"r");
    if(fp == 0) begin       // Failed to open file
        $display("Failed to open file \"%s\"!", `AUTOTB_TVIN_x_obs_old_3_V);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    read_token(fp, token);
    if (token != "[[[runtime]]]") begin
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    read_token(fp, token);
    while (token != "[[[/runtime]]]") begin
        if (token != "[[transaction]]") begin
            $display("ERROR: Simulation using HLS TB failed.");
              $finish;
        end
        read_token(fp, token);  // skip transaction number
          read_token(fp, token);
            # 0.2;
            while(ready_wire !== 1) begin
                @(posedge AESL_clock);
                # 0.2;
            end
        if(token != "[[/transaction]]") begin
            ret = $sscanf(token, "0x%x", AESL_REG_x_obs_old_3_V);
              if (ret != 1) begin
                  $display("Failed to parse token!");
                $display("ERROR: Simulation using HLS TB failed.");
                  $finish;
              end
            @(posedge AESL_clock);
              read_token(fp, token);
        end
          read_token(fp, token);
    end
    $fclose(fp);
end


// The signal of port x_obs_old_4_V
reg [15: 0] AESL_REG_x_obs_old_4_V = 0;
assign x_obs_old_4_V = AESL_REG_x_obs_old_4_V;
initial begin : read_file_process_x_obs_old_4_V
    integer fp;
    integer err;
    integer ret;
    integer proc_rand;
    reg [167  : 0] token;
    integer i;
    reg transaction_finish;
    integer transaction_idx;
    transaction_idx = 0;
    wait(AESL_reset === 0);
    fp = $fopen(`AUTOTB_TVIN_x_obs_old_4_V,"r");
    if(fp == 0) begin       // Failed to open file
        $display("Failed to open file \"%s\"!", `AUTOTB_TVIN_x_obs_old_4_V);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    read_token(fp, token);
    if (token != "[[[runtime]]]") begin
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    read_token(fp, token);
    while (token != "[[[/runtime]]]") begin
        if (token != "[[transaction]]") begin
            $display("ERROR: Simulation using HLS TB failed.");
              $finish;
        end
        read_token(fp, token);  // skip transaction number
          read_token(fp, token);
            # 0.2;
            while(ready_wire !== 1) begin
                @(posedge AESL_clock);
                # 0.2;
            end
        if(token != "[[/transaction]]") begin
            ret = $sscanf(token, "0x%x", AESL_REG_x_obs_old_4_V);
              if (ret != 1) begin
                  $display("Failed to parse token!");
                $display("ERROR: Simulation using HLS TB failed.");
                  $finish;
              end
            @(posedge AESL_clock);
              read_token(fp, token);
        end
          read_token(fp, token);
    end
    $fclose(fp);
end


// The signal of port x_obs_old_5_V
reg [15: 0] AESL_REG_x_obs_old_5_V = 0;
assign x_obs_old_5_V = AESL_REG_x_obs_old_5_V;
initial begin : read_file_process_x_obs_old_5_V
    integer fp;
    integer err;
    integer ret;
    integer proc_rand;
    reg [167  : 0] token;
    integer i;
    reg transaction_finish;
    integer transaction_idx;
    transaction_idx = 0;
    wait(AESL_reset === 0);
    fp = $fopen(`AUTOTB_TVIN_x_obs_old_5_V,"r");
    if(fp == 0) begin       // Failed to open file
        $display("Failed to open file \"%s\"!", `AUTOTB_TVIN_x_obs_old_5_V);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    read_token(fp, token);
    if (token != "[[[runtime]]]") begin
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    read_token(fp, token);
    while (token != "[[[/runtime]]]") begin
        if (token != "[[transaction]]") begin
            $display("ERROR: Simulation using HLS TB failed.");
              $finish;
        end
        read_token(fp, token);  // skip transaction number
          read_token(fp, token);
            # 0.2;
            while(ready_wire !== 1) begin
                @(posedge AESL_clock);
                # 0.2;
            end
        if(token != "[[/transaction]]") begin
            ret = $sscanf(token, "0x%x", AESL_REG_x_obs_old_5_V);
              if (ret != 1) begin
                  $display("Failed to parse token!");
                $display("ERROR: Simulation using HLS TB failed.");
                  $finish;
              end
            @(posedge AESL_clock);
              read_token(fp, token);
        end
          read_token(fp, token);
    end
    $fclose(fp);
end


reg AESL_REG_x_obs_0_o_V_ap_vld = 0;
// The signal of port x_obs_0_o_V
reg [15: 0] AESL_REG_x_obs_0_o_V = 0;
always @(posedge AESL_clock)
begin
    if(AESL_reset)
        AESL_REG_x_obs_0_o_V = 0; 
    else if(x_obs_0_o_V_ap_vld) begin
        AESL_REG_x_obs_0_o_V <= x_obs_0_o_V;
        AESL_REG_x_obs_0_o_V_ap_vld <= 1;
    end
end 

initial begin : write_file_process_x_obs_0_o_V
    integer fp;
    integer fp_size;
    integer err;
    integer ret;
    integer i;
    integer hls_stream_size;
    integer proc_rand;
    integer x_obs_0_o_V_count;
    reg [167:0] token;
    integer transaction_idx;
    reg [8 * 5:1] str;
    wait(AESL_reset === 0);
    fp = $fopen(`AUTOTB_TVOUT_x_obs_0_o_V_out_wrapc,"w");
    if(fp == 0) begin       // Failed to open file
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_x_obs_0_o_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    transaction_idx = 0;
    while (transaction_idx != AUTOTB_TRANSACTION_NUM) begin
        @(posedge AESL_clock);
          while(AESL_done !== 1) begin
              @(posedge AESL_clock);
          end
        # 0.4;
        $fdisplay(fp,"[[transaction]] %d", transaction_idx);
        if(AESL_REG_x_obs_0_o_V_ap_vld)  begin
          $fdisplay(fp,"0x%x", AESL_REG_x_obs_0_o_V);
        AESL_REG_x_obs_0_o_V_ap_vld = 0;
        end
    transaction_idx = transaction_idx + 1;
      $fdisplay(fp,"[[/transaction]]");
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
end


reg AESL_REG_x_obs_1_o_V_ap_vld = 0;
// The signal of port x_obs_1_o_V
reg [15: 0] AESL_REG_x_obs_1_o_V = 0;
always @(posedge AESL_clock)
begin
    if(AESL_reset)
        AESL_REG_x_obs_1_o_V = 0; 
    else if(x_obs_1_o_V_ap_vld) begin
        AESL_REG_x_obs_1_o_V <= x_obs_1_o_V;
        AESL_REG_x_obs_1_o_V_ap_vld <= 1;
    end
end 

initial begin : write_file_process_x_obs_1_o_V
    integer fp;
    integer fp_size;
    integer err;
    integer ret;
    integer i;
    integer hls_stream_size;
    integer proc_rand;
    integer x_obs_1_o_V_count;
    reg [167:0] token;
    integer transaction_idx;
    reg [8 * 5:1] str;
    wait(AESL_reset === 0);
    fp = $fopen(`AUTOTB_TVOUT_x_obs_1_o_V_out_wrapc,"w");
    if(fp == 0) begin       // Failed to open file
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_x_obs_1_o_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    transaction_idx = 0;
    while (transaction_idx != AUTOTB_TRANSACTION_NUM) begin
        @(posedge AESL_clock);
          while(AESL_done !== 1) begin
              @(posedge AESL_clock);
          end
        # 0.4;
        $fdisplay(fp,"[[transaction]] %d", transaction_idx);
        if(AESL_REG_x_obs_1_o_V_ap_vld)  begin
          $fdisplay(fp,"0x%x", AESL_REG_x_obs_1_o_V);
        AESL_REG_x_obs_1_o_V_ap_vld = 0;
        end
    transaction_idx = transaction_idx + 1;
      $fdisplay(fp,"[[/transaction]]");
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
end


reg AESL_REG_x_obs_2_o_V_ap_vld = 0;
// The signal of port x_obs_2_o_V
reg [15: 0] AESL_REG_x_obs_2_o_V = 0;
always @(posedge AESL_clock)
begin
    if(AESL_reset)
        AESL_REG_x_obs_2_o_V = 0; 
    else if(x_obs_2_o_V_ap_vld) begin
        AESL_REG_x_obs_2_o_V <= x_obs_2_o_V;
        AESL_REG_x_obs_2_o_V_ap_vld <= 1;
    end
end 

initial begin : write_file_process_x_obs_2_o_V
    integer fp;
    integer fp_size;
    integer err;
    integer ret;
    integer i;
    integer hls_stream_size;
    integer proc_rand;
    integer x_obs_2_o_V_count;
    reg [167:0] token;
    integer transaction_idx;
    reg [8 * 5:1] str;
    wait(AESL_reset === 0);
    fp = $fopen(`AUTOTB_TVOUT_x_obs_2_o_V_out_wrapc,"w");
    if(fp == 0) begin       // Failed to open file
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_x_obs_2_o_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    transaction_idx = 0;
    while (transaction_idx != AUTOTB_TRANSACTION_NUM) begin
        @(posedge AESL_clock);
          while(AESL_done !== 1) begin
              @(posedge AESL_clock);
          end
        # 0.4;
        $fdisplay(fp,"[[transaction]] %d", transaction_idx);
        if(AESL_REG_x_obs_2_o_V_ap_vld)  begin
          $fdisplay(fp,"0x%x", AESL_REG_x_obs_2_o_V);
        AESL_REG_x_obs_2_o_V_ap_vld = 0;
        end
    transaction_idx = transaction_idx + 1;
      $fdisplay(fp,"[[/transaction]]");
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
end


reg AESL_REG_x_obs_3_o_V_ap_vld = 0;
// The signal of port x_obs_3_o_V
reg [15: 0] AESL_REG_x_obs_3_o_V = 0;
always @(posedge AESL_clock)
begin
    if(AESL_reset)
        AESL_REG_x_obs_3_o_V = 0; 
    else if(x_obs_3_o_V_ap_vld) begin
        AESL_REG_x_obs_3_o_V <= x_obs_3_o_V;
        AESL_REG_x_obs_3_o_V_ap_vld <= 1;
    end
end 

initial begin : write_file_process_x_obs_3_o_V
    integer fp;
    integer fp_size;
    integer err;
    integer ret;
    integer i;
    integer hls_stream_size;
    integer proc_rand;
    integer x_obs_3_o_V_count;
    reg [167:0] token;
    integer transaction_idx;
    reg [8 * 5:1] str;
    wait(AESL_reset === 0);
    fp = $fopen(`AUTOTB_TVOUT_x_obs_3_o_V_out_wrapc,"w");
    if(fp == 0) begin       // Failed to open file
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_x_obs_3_o_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    transaction_idx = 0;
    while (transaction_idx != AUTOTB_TRANSACTION_NUM) begin
        @(posedge AESL_clock);
          while(AESL_done !== 1) begin
              @(posedge AESL_clock);
          end
        # 0.4;
        $fdisplay(fp,"[[transaction]] %d", transaction_idx);
        if(AESL_REG_x_obs_3_o_V_ap_vld)  begin
          $fdisplay(fp,"0x%x", AESL_REG_x_obs_3_o_V);
        AESL_REG_x_obs_3_o_V_ap_vld = 0;
        end
    transaction_idx = transaction_idx + 1;
      $fdisplay(fp,"[[/transaction]]");
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
end


reg AESL_REG_x_obs_4_o_V_ap_vld = 0;
// The signal of port x_obs_4_o_V
reg [15: 0] AESL_REG_x_obs_4_o_V = 0;
always @(posedge AESL_clock)
begin
    if(AESL_reset)
        AESL_REG_x_obs_4_o_V = 0; 
    else if(x_obs_4_o_V_ap_vld) begin
        AESL_REG_x_obs_4_o_V <= x_obs_4_o_V;
        AESL_REG_x_obs_4_o_V_ap_vld <= 1;
    end
end 

initial begin : write_file_process_x_obs_4_o_V
    integer fp;
    integer fp_size;
    integer err;
    integer ret;
    integer i;
    integer hls_stream_size;
    integer proc_rand;
    integer x_obs_4_o_V_count;
    reg [167:0] token;
    integer transaction_idx;
    reg [8 * 5:1] str;
    wait(AESL_reset === 0);
    fp = $fopen(`AUTOTB_TVOUT_x_obs_4_o_V_out_wrapc,"w");
    if(fp == 0) begin       // Failed to open file
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_x_obs_4_o_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    transaction_idx = 0;
    while (transaction_idx != AUTOTB_TRANSACTION_NUM) begin
        @(posedge AESL_clock);
          while(AESL_done !== 1) begin
              @(posedge AESL_clock);
          end
        # 0.4;
        $fdisplay(fp,"[[transaction]] %d", transaction_idx);
        if(AESL_REG_x_obs_4_o_V_ap_vld)  begin
          $fdisplay(fp,"0x%x", AESL_REG_x_obs_4_o_V);
        AESL_REG_x_obs_4_o_V_ap_vld = 0;
        end
    transaction_idx = transaction_idx + 1;
      $fdisplay(fp,"[[/transaction]]");
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
end


reg AESL_REG_x_obs_5_o_V_ap_vld = 0;
// The signal of port x_obs_5_o_V
reg [15: 0] AESL_REG_x_obs_5_o_V = 0;
always @(posedge AESL_clock)
begin
    if(AESL_reset)
        AESL_REG_x_obs_5_o_V = 0; 
    else if(x_obs_5_o_V_ap_vld) begin
        AESL_REG_x_obs_5_o_V <= x_obs_5_o_V;
        AESL_REG_x_obs_5_o_V_ap_vld <= 1;
    end
end 

initial begin : write_file_process_x_obs_5_o_V
    integer fp;
    integer fp_size;
    integer err;
    integer ret;
    integer i;
    integer hls_stream_size;
    integer proc_rand;
    integer x_obs_5_o_V_count;
    reg [167:0] token;
    integer transaction_idx;
    reg [8 * 5:1] str;
    wait(AESL_reset === 0);
    fp = $fopen(`AUTOTB_TVOUT_x_obs_5_o_V_out_wrapc,"w");
    if(fp == 0) begin       // Failed to open file
        $display("Failed to open file \"%s\"!", `AUTOTB_TVOUT_x_obs_5_o_V_out_wrapc);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    $fdisplay(fp,"[[[runtime]]]");
    transaction_idx = 0;
    while (transaction_idx != AUTOTB_TRANSACTION_NUM) begin
        @(posedge AESL_clock);
          while(AESL_done !== 1) begin
              @(posedge AESL_clock);
          end
        # 0.4;
        $fdisplay(fp,"[[transaction]] %d", transaction_idx);
        if(AESL_REG_x_obs_5_o_V_ap_vld)  begin
          $fdisplay(fp,"0x%x", AESL_REG_x_obs_5_o_V);
        AESL_REG_x_obs_5_o_V_ap_vld = 0;
        end
    transaction_idx = transaction_idx + 1;
      $fdisplay(fp,"[[/transaction]]");
    end
    $fdisplay(fp,"[[[/runtime]]]");
    $fclose(fp);
end


initial begin : generate_AESL_ready_cnt_proc
    AESL_ready_cnt = 0;
    wait(AESL_reset === 0);
    while(AESL_ready_cnt != AUTOTB_TRANSACTION_NUM) begin
        while(AESL_ready !== 1) begin
            @(posedge AESL_clock);
            # 0.4;
        end
        @(negedge AESL_clock);
        AESL_ready_cnt = AESL_ready_cnt + 1;
        @(posedge AESL_clock);
        # 0.4;
    end
end

    event next_trigger_ready_cnt;
    
    initial begin : gen_ready_cnt
        ready_cnt = 0;
        wait (AESL_reset === 0);
        forever begin
            @ (posedge AESL_clock);
            if (ready == 1) begin
                if (ready_cnt < AUTOTB_TRANSACTION_NUM) begin
                    ready_cnt = ready_cnt + 1;
                end
            end
            -> next_trigger_ready_cnt;
        end
    end
    
    wire all_finish = (done_cnt == AUTOTB_TRANSACTION_NUM);
    
    // done_cnt
    always @ (posedge AESL_clock) begin
        if (AESL_reset) begin
            done_cnt <= 0;
        end else begin
            if (AESL_done == 1) begin
                if (done_cnt < AUTOTB_TRANSACTION_NUM) begin
                    done_cnt <= done_cnt + 1;
                end
            end
        end
    end
    
    initial begin : finish_simulation
        wait (all_finish == 1);
        // last transaction is saved at negedge right after last done
        @ (posedge AESL_clock);
        @ (posedge AESL_clock);
        @ (posedge AESL_clock);
        @ (posedge AESL_clock);
        $finish;
    end
    
initial begin
    AESL_clock = 0;
    forever #`AUTOTB_CLOCK_PERIOD_DIV2 AESL_clock = ~AESL_clock;
end


reg end_x1_V;
reg [31:0] size_x1_V;
reg [31:0] size_x1_V_backup;
reg end_x2_V;
reg [31:0] size_x2_V;
reg [31:0] size_x2_V_backup;
reg end_u_1_V;
reg [31:0] size_u_1_V;
reg [31:0] size_u_1_V_backup;
reg end_u_2_V;
reg [31:0] size_u_2_V;
reg [31:0] size_u_2_V_backup;
reg end_x_obs_old_0_V;
reg [31:0] size_x_obs_old_0_V;
reg [31:0] size_x_obs_old_0_V_backup;
reg end_x_obs_old_1_V;
reg [31:0] size_x_obs_old_1_V;
reg [31:0] size_x_obs_old_1_V_backup;
reg end_x_obs_old_2_V;
reg [31:0] size_x_obs_old_2_V;
reg [31:0] size_x_obs_old_2_V_backup;
reg end_x_obs_old_3_V;
reg [31:0] size_x_obs_old_3_V;
reg [31:0] size_x_obs_old_3_V_backup;
reg end_x_obs_old_4_V;
reg [31:0] size_x_obs_old_4_V;
reg [31:0] size_x_obs_old_4_V_backup;
reg end_x_obs_old_5_V;
reg [31:0] size_x_obs_old_5_V;
reg [31:0] size_x_obs_old_5_V_backup;
reg end_x_obs_0_o_V;
reg [31:0] size_x_obs_0_o_V;
reg [31:0] size_x_obs_0_o_V_backup;
reg end_x_obs_1_o_V;
reg [31:0] size_x_obs_1_o_V;
reg [31:0] size_x_obs_1_o_V_backup;
reg end_x_obs_2_o_V;
reg [31:0] size_x_obs_2_o_V;
reg [31:0] size_x_obs_2_o_V_backup;
reg end_x_obs_3_o_V;
reg [31:0] size_x_obs_3_o_V;
reg [31:0] size_x_obs_3_o_V_backup;
reg end_x_obs_4_o_V;
reg [31:0] size_x_obs_4_o_V;
reg [31:0] size_x_obs_4_o_V_backup;
reg end_x_obs_5_o_V;
reg [31:0] size_x_obs_5_o_V;
reg [31:0] size_x_obs_5_o_V_backup;

initial begin : initial_process
    integer proc_rand;
    rst = 1;
    # 100;
    repeat(3) @ (posedge AESL_clock);
    rst = 0;
end
initial begin : start_process
    integer proc_rand;
    reg [31:0] start_cnt;
    ce = 1;
    start = 0;
    start_cnt = 0;
    wait (AESL_reset === 0);
    @ (posedge AESL_clock);
    #0 start = 1;
    start_cnt = start_cnt + 1;
    forever begin
        @ (posedge AESL_clock);
        if (start_cnt >= AUTOTB_TRANSACTION_NUM) begin
            // keep pushing garbage in
            #0 start = 1;
        end
        if (AESL_ready) begin
            start_cnt = start_cnt + 1;
        end
    end
end

always @(AESL_done)
begin
    tb_continue = AESL_done;
end

initial begin : ready_initial_process
    ready_initial = 0;
    wait (AESL_start === 1);
    ready_initial = 1;
    @(posedge AESL_clock);
    ready_initial = 0;
end

always @(posedge AESL_clock)
begin
    if(AESL_reset)
      AESL_ready_delay = 0;
  else
      AESL_ready_delay = AESL_ready;
end
initial begin : ready_last_n_process
  ready_last_n = 1;
  wait(ready_cnt == AUTOTB_TRANSACTION_NUM)
  @(posedge AESL_clock);
  ready_last_n <= 0;
end

always @(posedge AESL_clock)
begin
    if(AESL_reset)
      ready_delay_last_n = 0;
  else
      ready_delay_last_n <= ready_last_n;
end
assign ready = (ready_initial | AESL_ready_delay);
assign ready_wire = ready_initial | AESL_ready_delay;
initial begin : done_delay_last_n_process
  done_delay_last_n = 1;
  while(done_cnt < AUTOTB_TRANSACTION_NUM)
      @(posedge AESL_clock);
  # 0.1;
  done_delay_last_n = 0;
end

always @(posedge AESL_clock)
begin
    if(AESL_reset)
  begin
      AESL_done_delay <= 0;
      AESL_done_delay2 <= 0;
  end
  else begin
      AESL_done_delay <= AESL_done & done_delay_last_n;
      AESL_done_delay2 <= AESL_done_delay;
  end
end
always @(posedge AESL_clock)
begin
    if(AESL_reset)
      interface_done = 0;
  else begin
      # 0.01;
      if(ready === 1 && ready_cnt > 0 && ready_cnt < AUTOTB_TRANSACTION_NUM)
          interface_done = 1;
      else if(AESL_done_delay === 1 && done_cnt == AUTOTB_TRANSACTION_NUM)
          interface_done = 1;
      else
          interface_done = 0;
  end
end

////////////////////////////////////////////
// progress and performance
////////////////////////////////////////////

task wait_start();
    while (~AESL_start) begin
        @ (posedge AESL_clock);
    end
endtask

reg [31:0] clk_cnt = 0;
reg AESL_ready_p1;
reg AESL_start_p1;

always @ (posedge AESL_clock) begin
    clk_cnt <= clk_cnt + 1;
    AESL_ready_p1 <= AESL_ready;
    AESL_start_p1 <= AESL_start;
end

reg [31:0] start_timestamp [0:AUTOTB_TRANSACTION_NUM - 1];
reg [31:0] start_cnt;
reg [31:0] ready_timestamp [0:AUTOTB_TRANSACTION_NUM - 1];
reg [31:0] ap_ready_cnt;
reg [31:0] finish_timestamp [0:AUTOTB_TRANSACTION_NUM - 1];
reg [31:0] finish_cnt;
event report_progress;

initial begin
    start_cnt = 0;
    finish_cnt = 0;
    ap_ready_cnt = 0;
    wait (AESL_reset == 0);
    wait_start();
    start_timestamp[start_cnt] = clk_cnt;
    start_cnt = start_cnt + 1;
    if (AESL_done) begin
        finish_timestamp[finish_cnt] = clk_cnt;
        finish_cnt = finish_cnt + 1;
    end
    -> report_progress;
    forever begin
        @ (posedge AESL_clock);
        if (start_cnt < AUTOTB_TRANSACTION_NUM) begin
            if ((AESL_start && AESL_ready_p1)||(AESL_start && ~AESL_start_p1)) begin
                start_timestamp[start_cnt] = clk_cnt;
                start_cnt = start_cnt + 1;
            end
        end
        if (ap_ready_cnt < AUTOTB_TRANSACTION_NUM) begin
            if (AESL_start_p1 && AESL_ready_p1) begin
                ready_timestamp[ap_ready_cnt] = clk_cnt;
                ap_ready_cnt = ap_ready_cnt + 1;
            end
        end
        if (finish_cnt < AUTOTB_TRANSACTION_NUM) begin
            if (AESL_done) begin
                finish_timestamp[finish_cnt] = clk_cnt;
                finish_cnt = finish_cnt + 1;
            end
        end
        -> report_progress;
    end
end

reg [31:0] progress_timeout;

initial begin : simulation_progress
    real intra_progress;
    wait (AESL_reset == 0);
    progress_timeout = PROGRESS_TIMEOUT;
    $display("////////////////////////////////////////////////////////////////////////////////////");
    $display("// Inter-Transaction Progress: Completed Transaction / Total Transaction");
    $display("// Intra-Transaction Progress: Measured Latency / Latency Estimation * 100%%");
    $display("//");
    $display("// RTL Simulation : \"Inter-Transaction Progress\" [\"Intra-Transaction Progress\"] @ \"Simulation Time\"");
    $display("////////////////////////////////////////////////////////////////////////////////////");
    print_progress();
    while (finish_cnt < AUTOTB_TRANSACTION_NUM) begin
        @ (report_progress);
        if (finish_cnt < AUTOTB_TRANSACTION_NUM) begin
            if (AESL_done) begin
                print_progress();
                progress_timeout = PROGRESS_TIMEOUT;
            end else begin
                if (progress_timeout == 0) begin
                    print_progress();
                    progress_timeout = PROGRESS_TIMEOUT;
                end else begin
                    progress_timeout = progress_timeout - 1;
                end
            end
        end
    end
    print_progress();
    $display("////////////////////////////////////////////////////////////////////////////////////");
    calculate_performance();
end

task get_intra_progress(output real intra_progress);
    begin
        if (start_cnt > finish_cnt) begin
            intra_progress = clk_cnt - start_timestamp[finish_cnt];
        end else if(finish_cnt > 0) begin
            intra_progress = LATENCY_ESTIMATION;
        end else begin
            intra_progress = 0;
        end
        intra_progress = intra_progress / LATENCY_ESTIMATION;
    end
endtask

task print_progress();
    real intra_progress;
    begin
        if (LATENCY_ESTIMATION > 0) begin
            get_intra_progress(intra_progress);
            $display("// RTL Simulation : %0d / %0d [%2.2f%%] @ \"%0t\"", finish_cnt, AUTOTB_TRANSACTION_NUM, intra_progress * 100, $time);
        end else begin
            $display("// RTL Simulation : %0d / %0d [n/a] @ \"%0t\"", finish_cnt, AUTOTB_TRANSACTION_NUM, $time);
        end
    end
endtask

task calculate_performance();
    integer i;
    integer fp;
    reg [31:0] latency [0:AUTOTB_TRANSACTION_NUM - 1];
    reg [31:0] latency_min;
    reg [31:0] latency_max;
    reg [31:0] latency_total;
    reg [31:0] latency_average;
    reg [31:0] interval [0:AUTOTB_TRANSACTION_NUM - 2];
    reg [31:0] interval_min;
    reg [31:0] interval_max;
    reg [31:0] interval_total;
    reg [31:0] interval_average;
    begin
        latency_min = -1;
        latency_max = 0;
        latency_total = 0;
        interval_min = -1;
        interval_max = 0;
        interval_total = 0;

        for (i = 0; i < AUTOTB_TRANSACTION_NUM; i = i + 1) begin
            // calculate latency
            latency[i] = finish_timestamp[i] - start_timestamp[i];
            if (latency[i] > latency_max) latency_max = latency[i];
            if (latency[i] < latency_min) latency_min = latency[i];
            latency_total = latency_total + latency[i];
            // calculate interval
            if (AUTOTB_TRANSACTION_NUM == 1) begin
                interval[i] = 0;
                interval_max = 0;
                interval_min = 0;
                interval_total = 0;
            end else if (i < AUTOTB_TRANSACTION_NUM - 1) begin
                interval[i] = finish_timestamp[i] - start_timestamp[i]+1;
                if (interval[i] > interval_max) interval_max = interval[i];
                if (interval[i] < interval_min) interval_min = interval[i];
                interval_total = interval_total + interval[i];
            end
        end

        latency_average = latency_total / AUTOTB_TRANSACTION_NUM;
        if (AUTOTB_TRANSACTION_NUM == 1) begin
            interval_average = 0;
        end else begin
            interval_average = interval_total / (AUTOTB_TRANSACTION_NUM - 1);
        end

        fp = $fopen(`AUTOTB_LAT_RESULT_FILE, "w");

        $fdisplay(fp, "$MAX_LATENCY = \"%0d\"", latency_max);
        $fdisplay(fp, "$MIN_LATENCY = \"%0d\"", latency_min);
        $fdisplay(fp, "$AVER_LATENCY = \"%0d\"", latency_average);
        $fdisplay(fp, "$MAX_THROUGHPUT = \"%0d\"", interval_max);
        $fdisplay(fp, "$MIN_THROUGHPUT = \"%0d\"", interval_min);
        $fdisplay(fp, "$AVER_THROUGHPUT = \"%0d\"", interval_average);

        $fclose(fp);

        fp = $fopen(`AUTOTB_PER_RESULT_TRANS_FILE, "w");

        $fdisplay(fp, "%20s%16s%16s", "", "latency", "interval");
        if (AUTOTB_TRANSACTION_NUM == 1) begin
            i = 0;
            $fdisplay(fp, "transaction%8d:%16d%16d", i, latency[i], interval[i]);
        end else begin
            for (i = 0; i < AUTOTB_TRANSACTION_NUM; i = i + 1) begin
                if (i < AUTOTB_TRANSACTION_NUM - 1) begin
                    $fdisplay(fp, "transaction%8d:%16d%16d", i, latency[i], interval[i]);
                end else begin
                    $fdisplay(fp, "transaction%8d:%16d               x", i, latency[i]);
                end
            end
        end

        $fclose(fp);
    end
endtask


////////////////////////////////////////////
// Dependence Check
////////////////////////////////////////////

`ifndef POST_SYN

`endif

endmodule
