// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#define AP_INT_MAX_W 32678

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "setpoint_V"
#define AUTOTB_TVIN_setpoint_V  "../tv/cdatafile/c.PI_FF.autotvin_setpoint_V.dat"
// wrapc file define: "plant_in_V"
#define AUTOTB_TVIN_plant_in_V  "../tv/cdatafile/c.PI_FF.autotvin_plant_in_V.dat"
// wrapc file define: "error_V"
#define AUTOTB_TVOUT_error_V  "../tv/cdatafile/c.PI_FF.autotvout_error_V.dat"
// wrapc file define: "pi_out_V"
#define AUTOTB_TVOUT_pi_out_V  "../tv/cdatafile/c.PI_FF.autotvout_pi_out_V.dat"
// wrapc file define: "acc_out_V"
#define AUTOTB_TVIN_acc_out_V  "../tv/cdatafile/c.PI_FF.autotvin_acc_out_V.dat"
#define AUTOTB_TVOUT_acc_out_V  "../tv/cdatafile/c.PI_FF.autotvout_acc_out_V.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "error_V"
#define AUTOTB_TVOUT_PC_error_V  "../tv/rtldatafile/rtl.PI_FF.autotvout_error_V.dat"
// tvout file define: "pi_out_V"
#define AUTOTB_TVOUT_PC_pi_out_V  "../tv/rtldatafile/rtl.PI_FF.autotvout_pi_out_V.dat"
// tvout file define: "acc_out_V"
#define AUTOTB_TVOUT_PC_acc_out_V  "../tv/rtldatafile/rtl.PI_FF.autotvout_acc_out_V.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			setpoint_V_depth = 0;
			plant_in_V_depth = 0;
			error_V_depth = 0;
			pi_out_V_depth = 0;
			acc_out_V_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{setpoint_V " << setpoint_V_depth << "}\n";
			total_list << "{plant_in_V " << plant_in_V_depth << "}\n";
			total_list << "{error_V " << error_V_depth << "}\n";
			total_list << "{pi_out_V " << pi_out_V_depth << "}\n";
			total_list << "{acc_out_V " << acc_out_V_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int setpoint_V_depth;
		int plant_in_V_depth;
		int error_V_depth;
		int pi_out_V_depth;
		int acc_out_V_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};

extern void PI_FF (
ap_fixed<16, 8, (ap_q_mode) 0, (ap_o_mode)3, 0> setpoint,
ap_fixed<16, 8, (ap_q_mode) 0, (ap_o_mode)3, 0> plant_in,
ap_fixed<16, 8, (ap_q_mode) 0, (ap_o_mode)3, 0> (&error),
ap_fixed<16, 8, (ap_q_mode) 0, (ap_o_mode)3, 0> (&pi_out),
ap_fixed<16, 8, (ap_q_mode) 0, (ap_o_mode)3, 0> (&acc_out));

void AESL_WRAP_PI_FF (
ap_fixed<16, 8, (ap_q_mode) 0, (ap_o_mode)3, 0> setpoint,
ap_fixed<16, 8, (ap_q_mode) 0, (ap_o_mode)3, 0> plant_in,
ap_fixed<16, 8, (ap_q_mode) 0, (ap_o_mode)3, 0> (&error),
ap_fixed<16, 8, (ap_q_mode) 0, (ap_o_mode)3, 0> (&pi_out),
ap_fixed<16, 8, (ap_q_mode) 0, (ap_o_mode)3, 0> (&acc_out))
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;


		// output port post check: "error_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_error_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_error_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_error_V, AESL_token); // data

			sc_bv<16> *error_V_pc_buffer = new sc_bv<16>[1];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'error_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'error_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					error_V_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_error_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_error_V))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: error_V
				{
					// bitslice(15, 0)
					// {
						// celement: error.V(15, 0)
						// {
							sc_lv<16>* error_V_lv0_0_0_1 = new sc_lv<16>[1];
						// }
					// }

					// bitslice(15, 0)
					{
						int hls_map_index = 0;
						// celement: error.V(15, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								if (&(error) != NULL) // check the null address if the c port is array or others
								{
									error_V_lv0_0_0_1[hls_map_index].range(15, 0) = sc_bv<16>(error_V_pc_buffer[hls_map_index].range(15, 0));
									hls_map_index++;
								}
							}
						}
					}

					// bitslice(15, 0)
					{
						int hls_map_index = 0;
						// celement: error.V(15, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : error
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : error
								// output_left_conversion : (error).range()
								// output_type_conversion : (error_V_lv0_0_0_1[hls_map_index]).to_string(SC_BIN).c_str()
								if (&(error) != NULL) // check the null address if the c port is array or others
								{
									(error).range() = (error_V_lv0_0_0_1[hls_map_index]).to_string(SC_BIN).c_str();
									hls_map_index++;
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] error_V_pc_buffer;
		}

		// output port post check: "pi_out_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_pi_out_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_pi_out_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_pi_out_V, AESL_token); // data

			sc_bv<16> *pi_out_V_pc_buffer = new sc_bv<16>[1];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'pi_out_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'pi_out_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					pi_out_V_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_pi_out_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_pi_out_V))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: pi_out_V
				{
					// bitslice(15, 0)
					// {
						// celement: pi_out.V(15, 0)
						// {
							sc_lv<16>* pi_out_V_lv0_0_0_1 = new sc_lv<16>[1];
						// }
					// }

					// bitslice(15, 0)
					{
						int hls_map_index = 0;
						// celement: pi_out.V(15, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								if (&(pi_out) != NULL) // check the null address if the c port is array or others
								{
									pi_out_V_lv0_0_0_1[hls_map_index].range(15, 0) = sc_bv<16>(pi_out_V_pc_buffer[hls_map_index].range(15, 0));
									hls_map_index++;
								}
							}
						}
					}

					// bitslice(15, 0)
					{
						int hls_map_index = 0;
						// celement: pi_out.V(15, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : pi_out
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : pi_out
								// output_left_conversion : (pi_out).range()
								// output_type_conversion : (pi_out_V_lv0_0_0_1[hls_map_index]).to_string(SC_BIN).c_str()
								if (&(pi_out) != NULL) // check the null address if the c port is array or others
								{
									(pi_out).range() = (pi_out_V_lv0_0_0_1[hls_map_index]).to_string(SC_BIN).c_str();
									hls_map_index++;
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] pi_out_V_pc_buffer;
		}

		// output port post check: "acc_out_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_acc_out_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_acc_out_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_acc_out_V, AESL_token); // data

			sc_bv<16> *acc_out_V_pc_buffer = new sc_bv<16>[1];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'acc_out_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'acc_out_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					acc_out_V_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_acc_out_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_acc_out_V))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: acc_out_V
				{
					// bitslice(15, 0)
					// {
						// celement: acc_out.V(15, 0)
						// {
							sc_lv<16>* acc_out_V_lv0_0_0_1 = new sc_lv<16>[1];
						// }
					// }

					// bitslice(15, 0)
					{
						int hls_map_index = 0;
						// celement: acc_out.V(15, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								if (&(acc_out) != NULL) // check the null address if the c port is array or others
								{
									acc_out_V_lv0_0_0_1[hls_map_index].range(15, 0) = sc_bv<16>(acc_out_V_pc_buffer[hls_map_index].range(15, 0));
									hls_map_index++;
								}
							}
						}
					}

					// bitslice(15, 0)
					{
						int hls_map_index = 0;
						// celement: acc_out.V(15, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : acc_out
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : acc_out
								// output_left_conversion : (acc_out).range()
								// output_type_conversion : (acc_out_V_lv0_0_0_1[hls_map_index]).to_string(SC_BIN).c_str()
								if (&(acc_out) != NULL) // check the null address if the c port is array or others
								{
									(acc_out).range() = (acc_out_V_lv0_0_0_1[hls_map_index]).to_string(SC_BIN).c_str();
									hls_map_index++;
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] acc_out_V_pc_buffer;
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "setpoint_V"
		char* tvin_setpoint_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_setpoint_V);

		// "plant_in_V"
		char* tvin_plant_in_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_plant_in_V);

		// "error_V"
		char* tvout_error_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_error_V);

		// "pi_out_V"
		char* tvout_pi_out_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_pi_out_V);

		// "acc_out_V"
		char* tvin_acc_out_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_acc_out_V);
		char* tvout_acc_out_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_acc_out_V);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_setpoint_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_setpoint_V, tvin_setpoint_V);

		sc_bv<16> setpoint_V_tvin_wrapc_buffer;

		// RTL Name: setpoint_V
		{
			// bitslice(15, 0)
			{
				// celement: setpoint.V(15, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : setpoint
						// sub_1st_elem          : 
						// ori_name_1st_elem     : setpoint
						// regulate_c_name       : setpoint_V
						// input_type_conversion : (setpoint).range().to_string(SC_BIN).c_str()
						if (&(setpoint) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> setpoint_V_tmp_mem;
							setpoint_V_tmp_mem = (setpoint).range().to_string(SC_BIN).c_str();
							setpoint_V_tvin_wrapc_buffer.range(15, 0) = setpoint_V_tmp_mem.range(15, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_setpoint_V, "%s\n", (setpoint_V_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_setpoint_V, tvin_setpoint_V);
		}

		tcl_file.set_num(1, &tcl_file.setpoint_V_depth);
		sprintf(tvin_setpoint_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_setpoint_V, tvin_setpoint_V);

		// [[transaction]]
		sprintf(tvin_plant_in_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_plant_in_V, tvin_plant_in_V);

		sc_bv<16> plant_in_V_tvin_wrapc_buffer;

		// RTL Name: plant_in_V
		{
			// bitslice(15, 0)
			{
				// celement: plant_in.V(15, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : plant_in
						// sub_1st_elem          : 
						// ori_name_1st_elem     : plant_in
						// regulate_c_name       : plant_in_V
						// input_type_conversion : (plant_in).range().to_string(SC_BIN).c_str()
						if (&(plant_in) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> plant_in_V_tmp_mem;
							plant_in_V_tmp_mem = (plant_in).range().to_string(SC_BIN).c_str();
							plant_in_V_tvin_wrapc_buffer.range(15, 0) = plant_in_V_tmp_mem.range(15, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_plant_in_V, "%s\n", (plant_in_V_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_plant_in_V, tvin_plant_in_V);
		}

		tcl_file.set_num(1, &tcl_file.plant_in_V_depth);
		sprintf(tvin_plant_in_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_plant_in_V, tvin_plant_in_V);

		// [[transaction]]
		sprintf(tvin_acc_out_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_acc_out_V, tvin_acc_out_V);

		sc_bv<16>* acc_out_V_tvin_wrapc_buffer = new sc_bv<16>[1];

		// RTL Name: acc_out_V
		{
			// bitslice(15, 0)
			{
				int hls_map_index = 0;
				// celement: acc_out.V(15, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : acc_out
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : acc_out
						// regulate_c_name       : acc_out_V
						// input_type_conversion : (acc_out).range().to_string(SC_BIN).c_str()
						if (&(acc_out) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> acc_out_V_tmp_mem;
							acc_out_V_tmp_mem = (acc_out).range().to_string(SC_BIN).c_str();
							acc_out_V_tvin_wrapc_buffer[hls_map_index].range(15, 0) = acc_out_V_tmp_mem.range(15, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_acc_out_V, "%s\n", (acc_out_V_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_acc_out_V, tvin_acc_out_V);
		}

		tcl_file.set_num(1, &tcl_file.acc_out_V_depth);
		sprintf(tvin_acc_out_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_acc_out_V, tvin_acc_out_V);

		// release memory allocation
		delete [] acc_out_V_tvin_wrapc_buffer;

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		PI_FF(setpoint, plant_in, error, pi_out, acc_out);

		CodeState = DUMP_OUTPUTS;

		// [[transaction]]
		sprintf(tvout_error_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_error_V, tvout_error_V);

		sc_bv<16>* error_V_tvout_wrapc_buffer = new sc_bv<16>[1];

		// RTL Name: error_V
		{
			// bitslice(15, 0)
			{
				int hls_map_index = 0;
				// celement: error.V(15, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : error
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : error
						// regulate_c_name       : error_V
						// input_type_conversion : (error).range().to_string(SC_BIN).c_str()
						if (&(error) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> error_V_tmp_mem;
							error_V_tmp_mem = (error).range().to_string(SC_BIN).c_str();
							error_V_tvout_wrapc_buffer[hls_map_index].range(15, 0) = error_V_tmp_mem.range(15, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_error_V, "%s\n", (error_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_error_V, tvout_error_V);
		}

		tcl_file.set_num(1, &tcl_file.error_V_depth);
		sprintf(tvout_error_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_error_V, tvout_error_V);

		// release memory allocation
		delete [] error_V_tvout_wrapc_buffer;

		// [[transaction]]
		sprintf(tvout_pi_out_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_pi_out_V, tvout_pi_out_V);

		sc_bv<16>* pi_out_V_tvout_wrapc_buffer = new sc_bv<16>[1];

		// RTL Name: pi_out_V
		{
			// bitslice(15, 0)
			{
				int hls_map_index = 0;
				// celement: pi_out.V(15, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : pi_out
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : pi_out
						// regulate_c_name       : pi_out_V
						// input_type_conversion : (pi_out).range().to_string(SC_BIN).c_str()
						if (&(pi_out) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> pi_out_V_tmp_mem;
							pi_out_V_tmp_mem = (pi_out).range().to_string(SC_BIN).c_str();
							pi_out_V_tvout_wrapc_buffer[hls_map_index].range(15, 0) = pi_out_V_tmp_mem.range(15, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_pi_out_V, "%s\n", (pi_out_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_pi_out_V, tvout_pi_out_V);
		}

		tcl_file.set_num(1, &tcl_file.pi_out_V_depth);
		sprintf(tvout_pi_out_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_pi_out_V, tvout_pi_out_V);

		// release memory allocation
		delete [] pi_out_V_tvout_wrapc_buffer;

		// [[transaction]]
		sprintf(tvout_acc_out_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_acc_out_V, tvout_acc_out_V);

		sc_bv<16>* acc_out_V_tvout_wrapc_buffer = new sc_bv<16>[1];

		// RTL Name: acc_out_V
		{
			// bitslice(15, 0)
			{
				int hls_map_index = 0;
				// celement: acc_out.V(15, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : acc_out
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : acc_out
						// regulate_c_name       : acc_out_V
						// input_type_conversion : (acc_out).range().to_string(SC_BIN).c_str()
						if (&(acc_out) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> acc_out_V_tmp_mem;
							acc_out_V_tmp_mem = (acc_out).range().to_string(SC_BIN).c_str();
							acc_out_V_tvout_wrapc_buffer[hls_map_index].range(15, 0) = acc_out_V_tmp_mem.range(15, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_acc_out_V, "%s\n", (acc_out_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_acc_out_V, tvout_acc_out_V);
		}

		tcl_file.set_num(1, &tcl_file.acc_out_V_depth);
		sprintf(tvout_acc_out_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_acc_out_V, tvout_acc_out_V);

		// release memory allocation
		delete [] acc_out_V_tvout_wrapc_buffer;

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "setpoint_V"
		delete [] tvin_setpoint_V;
		// release memory allocation: "plant_in_V"
		delete [] tvin_plant_in_V;
		// release memory allocation: "error_V"
		delete [] tvout_error_V;
		// release memory allocation: "pi_out_V"
		delete [] tvout_pi_out_V;
		// release memory allocation: "acc_out_V"
		delete [] tvin_acc_out_V;
		delete [] tvout_acc_out_V;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

