// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#define AP_INT_MAX_W 32678

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "x_in_V"
#define AUTOTB_TVIN_x_in_V  "../tv/cdatafile/c.QP.autotvin_x_in_V.dat"
// wrapc file define: "z_1_V"
#define AUTOTB_TVOUT_z_1_V  "../tv/cdatafile/c.QP.autotvout_z_1_V.dat"
// wrapc file define: "z_2_V"
#define AUTOTB_TVOUT_z_2_V  "../tv/cdatafile/c.QP.autotvout_z_2_V.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "z_1_V"
#define AUTOTB_TVOUT_PC_z_1_V  "../tv/rtldatafile/rtl.QP.autotvout_z_1_V.dat"
// tvout file define: "z_2_V"
#define AUTOTB_TVOUT_PC_z_2_V  "../tv/rtldatafile/rtl.QP.autotvout_z_2_V.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			x_in_V_depth = 0;
			z_1_V_depth = 0;
			z_2_V_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{x_in_V " << x_in_V_depth << "}\n";
			total_list << "{z_1_V " << z_1_V_depth << "}\n";
			total_list << "{z_2_V " << z_2_V_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int x_in_V_depth;
		int z_1_V_depth;
		int z_2_V_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};

extern void QP (
ap_fixed<16, 8, (ap_q_mode) 0, (ap_o_mode)3, 0> x_in,
ap_fixed<16, 8, (ap_q_mode) 0, (ap_o_mode)3, 0> (&z_1),
ap_fixed<16, 8, (ap_q_mode) 0, (ap_o_mode)3, 0> (&z_2));

void AESL_WRAP_QP (
ap_fixed<16, 8, (ap_q_mode) 0, (ap_o_mode)3, 0> x_in,
ap_fixed<16, 8, (ap_q_mode) 0, (ap_o_mode)3, 0> (&z_1),
ap_fixed<16, 8, (ap_q_mode) 0, (ap_o_mode)3, 0> (&z_2))
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;


		// output port post check: "z_1_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_z_1_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_z_1_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_z_1_V, AESL_token); // data

			sc_bv<16> *z_1_V_pc_buffer = new sc_bv<16>[1];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'z_1_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'z_1_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					z_1_V_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_z_1_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_z_1_V))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: z_1_V
				{
					// bitslice(15, 0)
					// {
						// celement: z_1.V(15, 0)
						// {
							sc_lv<16>* z_1_V_lv0_0_0_1 = new sc_lv<16>[1];
						// }
					// }

					// bitslice(15, 0)
					{
						int hls_map_index = 0;
						// celement: z_1.V(15, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								if (&(z_1) != NULL) // check the null address if the c port is array or others
								{
									z_1_V_lv0_0_0_1[hls_map_index].range(15, 0) = sc_bv<16>(z_1_V_pc_buffer[hls_map_index].range(15, 0));
									hls_map_index++;
								}
							}
						}
					}

					// bitslice(15, 0)
					{
						int hls_map_index = 0;
						// celement: z_1.V(15, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : z_1
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : z_1
								// output_left_conversion : (z_1).range()
								// output_type_conversion : (z_1_V_lv0_0_0_1[hls_map_index]).to_string(SC_BIN).c_str()
								if (&(z_1) != NULL) // check the null address if the c port is array or others
								{
									(z_1).range() = (z_1_V_lv0_0_0_1[hls_map_index]).to_string(SC_BIN).c_str();
									hls_map_index++;
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] z_1_V_pc_buffer;
		}

		// output port post check: "z_2_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_z_2_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_z_2_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_z_2_V, AESL_token); // data

			sc_bv<16> *z_2_V_pc_buffer = new sc_bv<16>[1];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'z_2_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'z_2_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					z_2_V_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_z_2_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_z_2_V))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: z_2_V
				{
					// bitslice(15, 0)
					// {
						// celement: z_2.V(15, 0)
						// {
							sc_lv<16>* z_2_V_lv0_0_0_1 = new sc_lv<16>[1];
						// }
					// }

					// bitslice(15, 0)
					{
						int hls_map_index = 0;
						// celement: z_2.V(15, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								if (&(z_2) != NULL) // check the null address if the c port is array or others
								{
									z_2_V_lv0_0_0_1[hls_map_index].range(15, 0) = sc_bv<16>(z_2_V_pc_buffer[hls_map_index].range(15, 0));
									hls_map_index++;
								}
							}
						}
					}

					// bitslice(15, 0)
					{
						int hls_map_index = 0;
						// celement: z_2.V(15, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : z_2
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : z_2
								// output_left_conversion : (z_2).range()
								// output_type_conversion : (z_2_V_lv0_0_0_1[hls_map_index]).to_string(SC_BIN).c_str()
								if (&(z_2) != NULL) // check the null address if the c port is array or others
								{
									(z_2).range() = (z_2_V_lv0_0_0_1[hls_map_index]).to_string(SC_BIN).c_str();
									hls_map_index++;
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] z_2_V_pc_buffer;
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "x_in_V"
		char* tvin_x_in_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_x_in_V);

		// "z_1_V"
		char* tvout_z_1_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_z_1_V);

		// "z_2_V"
		char* tvout_z_2_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_z_2_V);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_x_in_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_x_in_V, tvin_x_in_V);

		sc_bv<16> x_in_V_tvin_wrapc_buffer;

		// RTL Name: x_in_V
		{
			// bitslice(15, 0)
			{
				// celement: x_in.V(15, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : x_in
						// sub_1st_elem          : 
						// ori_name_1st_elem     : x_in
						// regulate_c_name       : x_in_V
						// input_type_conversion : (x_in).range().to_string(SC_BIN).c_str()
						if (&(x_in) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> x_in_V_tmp_mem;
							x_in_V_tmp_mem = (x_in).range().to_string(SC_BIN).c_str();
							x_in_V_tvin_wrapc_buffer.range(15, 0) = x_in_V_tmp_mem.range(15, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_x_in_V, "%s\n", (x_in_V_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_x_in_V, tvin_x_in_V);
		}

		tcl_file.set_num(1, &tcl_file.x_in_V_depth);
		sprintf(tvin_x_in_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_x_in_V, tvin_x_in_V);

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		QP(x_in, z_1, z_2);

		CodeState = DUMP_OUTPUTS;

		// [[transaction]]
		sprintf(tvout_z_1_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_z_1_V, tvout_z_1_V);

		sc_bv<16>* z_1_V_tvout_wrapc_buffer = new sc_bv<16>[1];

		// RTL Name: z_1_V
		{
			// bitslice(15, 0)
			{
				int hls_map_index = 0;
				// celement: z_1.V(15, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : z_1
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : z_1
						// regulate_c_name       : z_1_V
						// input_type_conversion : (z_1).range().to_string(SC_BIN).c_str()
						if (&(z_1) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> z_1_V_tmp_mem;
							z_1_V_tmp_mem = (z_1).range().to_string(SC_BIN).c_str();
							z_1_V_tvout_wrapc_buffer[hls_map_index].range(15, 0) = z_1_V_tmp_mem.range(15, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_z_1_V, "%s\n", (z_1_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_z_1_V, tvout_z_1_V);
		}

		tcl_file.set_num(1, &tcl_file.z_1_V_depth);
		sprintf(tvout_z_1_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_z_1_V, tvout_z_1_V);

		// release memory allocation
		delete [] z_1_V_tvout_wrapc_buffer;

		// [[transaction]]
		sprintf(tvout_z_2_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_z_2_V, tvout_z_2_V);

		sc_bv<16>* z_2_V_tvout_wrapc_buffer = new sc_bv<16>[1];

		// RTL Name: z_2_V
		{
			// bitslice(15, 0)
			{
				int hls_map_index = 0;
				// celement: z_2.V(15, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : z_2
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : z_2
						// regulate_c_name       : z_2_V
						// input_type_conversion : (z_2).range().to_string(SC_BIN).c_str()
						if (&(z_2) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> z_2_V_tmp_mem;
							z_2_V_tmp_mem = (z_2).range().to_string(SC_BIN).c_str();
							z_2_V_tvout_wrapc_buffer[hls_map_index].range(15, 0) = z_2_V_tmp_mem.range(15, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_z_2_V, "%s\n", (z_2_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_z_2_V, tvout_z_2_V);
		}

		tcl_file.set_num(1, &tcl_file.z_2_V_depth);
		sprintf(tvout_z_2_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_z_2_V, tvout_z_2_V);

		// release memory allocation
		delete [] z_2_V_tvout_wrapc_buffer;

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "x_in_V"
		delete [] tvin_x_in_V;
		// release memory allocation: "z_1_V"
		delete [] tvout_z_1_V;
		// release memory allocation: "z_2_V"
		delete [] tvout_z_2_V;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

