// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "matrix_multiply_defa_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic matrix_multiply_defa_1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic matrix_multiply_defa_1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> matrix_multiply_defa_1::ap_ST_fsm_state1 = "1";
const sc_lv<3> matrix_multiply_defa_1::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> matrix_multiply_defa_1::ap_ST_fsm_state6 = "100";
const bool matrix_multiply_defa_1::ap_const_boolean_1 = true;
const sc_lv<32> matrix_multiply_defa_1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> matrix_multiply_defa_1::ap_const_lv32_1 = "1";
const bool matrix_multiply_defa_1::ap_const_boolean_0 = false;
const sc_lv<1> matrix_multiply_defa_1::ap_const_lv1_0 = "0";
const sc_lv<1> matrix_multiply_defa_1::ap_const_lv1_1 = "1";
const sc_lv<7> matrix_multiply_defa_1::ap_const_lv7_0 = "0000000";
const sc_lv<5> matrix_multiply_defa_1::ap_const_lv5_0 = "00000";
const sc_lv<3> matrix_multiply_defa_1::ap_const_lv3_0 = "000";
const sc_lv<7> matrix_multiply_defa_1::ap_const_lv7_50 = "1010000";
const sc_lv<7> matrix_multiply_defa_1::ap_const_lv7_1 = "1";
const sc_lv<5> matrix_multiply_defa_1::ap_const_lv5_1 = "1";
const sc_lv<3> matrix_multiply_defa_1::ap_const_lv3_4 = "100";
const sc_lv<2> matrix_multiply_defa_1::ap_const_lv2_0 = "00";
const sc_lv<3> matrix_multiply_defa_1::ap_const_lv3_3 = "11";
const sc_lv<3> matrix_multiply_defa_1::ap_const_lv3_1 = "1";
const sc_lv<32> matrix_multiply_defa_1::ap_const_lv32_8 = "1000";
const sc_lv<32> matrix_multiply_defa_1::ap_const_lv32_17 = "10111";
const sc_lv<32> matrix_multiply_defa_1::ap_const_lv32_7 = "111";
const sc_lv<32> matrix_multiply_defa_1::ap_const_lv32_2 = "10";

matrix_multiply_defa_1::matrix_multiply_defa_1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    F1_V_U = new matrix_multiply_ddEe("F1_V_U");
    F1_V_U->clk(ap_clk);
    F1_V_U->reset(ap_rst);
    F1_V_U->address0(F1_V_address0);
    F1_V_U->ce0(F1_V_ce0);
    F1_V_U->q0(F1_V_q0);
    PrimalDual_mux_42eOg_U7 = new PrimalDual_mux_42eOg<1,1,16,16,16,16,2,16>("PrimalDual_mux_42eOg_U7");
    PrimalDual_mux_42eOg_U7->din0(B_0_0_V_read);
    PrimalDual_mux_42eOg_U7->din1(B_0_1_V_read);
    PrimalDual_mux_42eOg_U7->din2(B_0_2_V_read);
    PrimalDual_mux_42eOg_U7->din3(B_0_3_V_read);
    PrimalDual_mux_42eOg_U7->din4(tmp_2_reg_368);
    PrimalDual_mux_42eOg_U7->dout(tmp_1_fu_244_p6);
    PrimalDual_mul_mufYi_U8 = new PrimalDual_mul_mufYi<1,1,16,8,24>("PrimalDual_mul_mufYi_U8");
    PrimalDual_mul_mufYi_U8->din0(tmp_1_reg_392);
    PrimalDual_mul_mufYi_U8->din1(r_V_fu_316_p1);
    PrimalDual_mul_mufYi_U8->dout(r_V_fu_316_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_C_0_V_address0);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_mid2_fu_262_p1 );

    SC_METHOD(thread_C_0_V_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_C_0_V_d0);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_6_fu_305_p1 );
    sensitive << ( p_Val2_s_fu_287_p4 );

    SC_METHOD(thread_C_0_V_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_s_reg_378_pp0_iter2_reg );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_Col_assign_mid2_fu_179_p3);
    sensitive << ( Col_assign_reg_144 );
    sensitive << ( exitcond4_fu_173_p2 );

    SC_METHOD(thread_F1_V_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_3_cast_fu_217_p1 );

    SC_METHOD(thread_F1_V_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter3);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( exitcond_flatten_fu_155_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_ap_phi_mux_Row_assign_phi_fu_137_p4);
    sensitive << ( Row_assign_reg_133 );
    sensitive << ( exitcond_flatten_reg_348 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( tmp_mid2_v_reg_357 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_exitcond4_fu_173_p2);
    sensitive << ( Col_assign_reg_144 );
    sensitive << ( exitcond_flatten_fu_155_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_exitcond_flatten_fu_155_p2);
    sensitive << ( indvar_flatten_reg_122 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_indvar_flatten_next_fu_161_p2);
    sensitive << ( indvar_flatten_reg_122 );

    SC_METHOD(thread_k_2_fu_238_p2);
    sensitive << ( Col_assign_mid2_fu_179_p3 );

    SC_METHOD(thread_p_Val2_8_fu_266_p1);
    sensitive << ( r_V_reg_397 );

    SC_METHOD(thread_p_Val2_9_fu_269_p2);
    sensitive << ( p_Val2_7_fu_68 );
    sensitive << ( p_Val2_8_fu_266_p1 );

    SC_METHOD(thread_p_Val2_s_fu_287_p4);
    sensitive << ( sum_mult_V_fu_275_p3 );

    SC_METHOD(thread_r_V_fu_316_p1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( r_V_fu_316_p10 );

    SC_METHOD(thread_r_V_fu_316_p10);
    sensitive << ( F1_V_load_reg_387 );

    SC_METHOD(thread_r_fu_167_p2);
    sensitive << ( ap_phi_mux_Row_assign_phi_fu_137_p4 );

    SC_METHOD(thread_sum_mult_V_fu_275_p3);
    sensitive << ( tmp_9_reg_373_pp0_iter2_reg );
    sensitive << ( p_Val2_8_fu_266_p1 );
    sensitive << ( p_Val2_9_fu_269_p2 );

    SC_METHOD(thread_tmp_2_cast_fu_203_p1);
    sensitive << ( tmp_fu_195_p3 );

    SC_METHOD(thread_tmp_2_fu_222_p1);
    sensitive << ( Col_assign_mid2_fu_179_p3 );

    SC_METHOD(thread_tmp_3_cast_fu_217_p1);
    sensitive << ( tmp_3_fu_211_p2 );

    SC_METHOD(thread_tmp_3_fu_211_p2);
    sensitive << ( tmp_2_cast_fu_203_p1 );
    sensitive << ( tmp_i_i_cast_fu_207_p1 );

    SC_METHOD(thread_tmp_5_fu_297_p3);
    sensitive << ( sum_mult_V_fu_275_p3 );

    SC_METHOD(thread_tmp_6_fu_305_p1);
    sensitive << ( tmp_5_fu_297_p3 );

    SC_METHOD(thread_tmp_9_fu_226_p2);
    sensitive << ( exitcond_flatten_fu_155_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( Col_assign_mid2_fu_179_p3 );

    SC_METHOD(thread_tmp_fu_195_p3);
    sensitive << ( tmp_mid2_v_fu_187_p3 );

    SC_METHOD(thread_tmp_i_i_cast_fu_207_p1);
    sensitive << ( Col_assign_mid2_fu_179_p3 );

    SC_METHOD(thread_tmp_mid2_fu_262_p1);
    sensitive << ( tmp_mid2_v_reg_357_pp0_iter2_reg );

    SC_METHOD(thread_tmp_mid2_v_fu_187_p3);
    sensitive << ( ap_phi_mux_Row_assign_phi_fu_137_p4 );
    sensitive << ( exitcond4_fu_173_p2 );
    sensitive << ( r_fu_167_p2 );

    SC_METHOD(thread_tmp_s_fu_232_p2);
    sensitive << ( exitcond_flatten_fu_155_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( Col_assign_mid2_fu_179_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( exitcond_flatten_fu_155_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "matrix_multiply_defa_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, B_0_0_V_read, "(port)B_0_0_V_read");
    sc_trace(mVcdFile, B_0_1_V_read, "(port)B_0_1_V_read");
    sc_trace(mVcdFile, B_0_2_V_read, "(port)B_0_2_V_read");
    sc_trace(mVcdFile, B_0_3_V_read, "(port)B_0_3_V_read");
    sc_trace(mVcdFile, C_0_V_address0, "(port)C_0_V_address0");
    sc_trace(mVcdFile, C_0_V_ce0, "(port)C_0_V_ce0");
    sc_trace(mVcdFile, C_0_V_we0, "(port)C_0_V_we0");
    sc_trace(mVcdFile, C_0_V_d0, "(port)C_0_V_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, F1_V_address0, "F1_V_address0");
    sc_trace(mVcdFile, F1_V_ce0, "F1_V_ce0");
    sc_trace(mVcdFile, F1_V_q0, "F1_V_q0");
    sc_trace(mVcdFile, indvar_flatten_reg_122, "indvar_flatten_reg_122");
    sc_trace(mVcdFile, Row_assign_reg_133, "Row_assign_reg_133");
    sc_trace(mVcdFile, Col_assign_reg_144, "Col_assign_reg_144");
    sc_trace(mVcdFile, exitcond_flatten_fu_155_p2, "exitcond_flatten_fu_155_p2");
    sc_trace(mVcdFile, exitcond_flatten_reg_348, "exitcond_flatten_reg_348");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter3, "ap_block_state5_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, exitcond_flatten_reg_348_pp0_iter1_reg, "exitcond_flatten_reg_348_pp0_iter1_reg");
    sc_trace(mVcdFile, exitcond_flatten_reg_348_pp0_iter2_reg, "exitcond_flatten_reg_348_pp0_iter2_reg");
    sc_trace(mVcdFile, indvar_flatten_next_fu_161_p2, "indvar_flatten_next_fu_161_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_mid2_v_fu_187_p3, "tmp_mid2_v_fu_187_p3");
    sc_trace(mVcdFile, tmp_mid2_v_reg_357, "tmp_mid2_v_reg_357");
    sc_trace(mVcdFile, tmp_mid2_v_reg_357_pp0_iter1_reg, "tmp_mid2_v_reg_357_pp0_iter1_reg");
    sc_trace(mVcdFile, tmp_mid2_v_reg_357_pp0_iter2_reg, "tmp_mid2_v_reg_357_pp0_iter2_reg");
    sc_trace(mVcdFile, tmp_2_fu_222_p1, "tmp_2_fu_222_p1");
    sc_trace(mVcdFile, tmp_2_reg_368, "tmp_2_reg_368");
    sc_trace(mVcdFile, tmp_9_fu_226_p2, "tmp_9_fu_226_p2");
    sc_trace(mVcdFile, tmp_9_reg_373, "tmp_9_reg_373");
    sc_trace(mVcdFile, tmp_9_reg_373_pp0_iter1_reg, "tmp_9_reg_373_pp0_iter1_reg");
    sc_trace(mVcdFile, tmp_9_reg_373_pp0_iter2_reg, "tmp_9_reg_373_pp0_iter2_reg");
    sc_trace(mVcdFile, tmp_s_fu_232_p2, "tmp_s_fu_232_p2");
    sc_trace(mVcdFile, tmp_s_reg_378, "tmp_s_reg_378");
    sc_trace(mVcdFile, tmp_s_reg_378_pp0_iter1_reg, "tmp_s_reg_378_pp0_iter1_reg");
    sc_trace(mVcdFile, tmp_s_reg_378_pp0_iter2_reg, "tmp_s_reg_378_pp0_iter2_reg");
    sc_trace(mVcdFile, k_2_fu_238_p2, "k_2_fu_238_p2");
    sc_trace(mVcdFile, F1_V_load_reg_387, "F1_V_load_reg_387");
    sc_trace(mVcdFile, tmp_1_fu_244_p6, "tmp_1_fu_244_p6");
    sc_trace(mVcdFile, tmp_1_reg_392, "tmp_1_reg_392");
    sc_trace(mVcdFile, r_V_fu_316_p2, "r_V_fu_316_p2");
    sc_trace(mVcdFile, r_V_reg_397, "r_V_reg_397");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_phi_mux_Row_assign_phi_fu_137_p4, "ap_phi_mux_Row_assign_phi_fu_137_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, tmp_3_cast_fu_217_p1, "tmp_3_cast_fu_217_p1");
    sc_trace(mVcdFile, tmp_mid2_fu_262_p1, "tmp_mid2_fu_262_p1");
    sc_trace(mVcdFile, p_Val2_7_fu_68, "p_Val2_7_fu_68");
    sc_trace(mVcdFile, sum_mult_V_fu_275_p3, "sum_mult_V_fu_275_p3");
    sc_trace(mVcdFile, exitcond4_fu_173_p2, "exitcond4_fu_173_p2");
    sc_trace(mVcdFile, r_fu_167_p2, "r_fu_167_p2");
    sc_trace(mVcdFile, tmp_fu_195_p3, "tmp_fu_195_p3");
    sc_trace(mVcdFile, Col_assign_mid2_fu_179_p3, "Col_assign_mid2_fu_179_p3");
    sc_trace(mVcdFile, tmp_2_cast_fu_203_p1, "tmp_2_cast_fu_203_p1");
    sc_trace(mVcdFile, tmp_i_i_cast_fu_207_p1, "tmp_i_i_cast_fu_207_p1");
    sc_trace(mVcdFile, tmp_3_fu_211_p2, "tmp_3_fu_211_p2");
    sc_trace(mVcdFile, p_Val2_8_fu_266_p1, "p_Val2_8_fu_266_p1");
    sc_trace(mVcdFile, p_Val2_9_fu_269_p2, "p_Val2_9_fu_269_p2");
    sc_trace(mVcdFile, tmp_5_fu_297_p3, "tmp_5_fu_297_p3");
    sc_trace(mVcdFile, tmp_6_fu_305_p1, "tmp_6_fu_305_p1");
    sc_trace(mVcdFile, p_Val2_s_fu_287_p4, "p_Val2_s_fu_287_p4");
    sc_trace(mVcdFile, r_V_fu_316_p1, "r_V_fu_316_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, r_V_fu_316_p10, "r_V_fu_316_p10");
#endif

    }
}

matrix_multiply_defa_1::~matrix_multiply_defa_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete F1_V_U;
    delete PrimalDual_mux_42eOg_U7;
    delete PrimalDual_mul_mufYi_U8;
}

void matrix_multiply_defa_1::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(exitcond_flatten_fu_155_p2.read(), ap_const_lv1_0))) {
        Col_assign_reg_144 = k_2_fu_238_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        Col_assign_reg_144 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_348.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        Row_assign_reg_133 = tmp_mid2_v_reg_357.read();
    } else if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        Row_assign_reg_133 = ap_const_lv5_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        } else if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
            ap_enable_reg_pp0_iter3 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(exitcond_flatten_fu_155_p2.read(), ap_const_lv1_0))) {
        indvar_flatten_reg_122 = indvar_flatten_next_fu_161_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        indvar_flatten_reg_122 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_reg_348.read(), ap_const_lv1_0))) {
        F1_V_load_reg_387 = F1_V_q0.read();
        tmp_1_reg_392 = tmp_1_fu_244_p6.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond_flatten_reg_348 = exitcond_flatten_fu_155_p2.read();
        exitcond_flatten_reg_348_pp0_iter1_reg = exitcond_flatten_reg_348.read();
        tmp_9_reg_373_pp0_iter1_reg = tmp_9_reg_373.read();
        tmp_mid2_v_reg_357_pp0_iter1_reg = tmp_mid2_v_reg_357.read();
        tmp_s_reg_378_pp0_iter1_reg = tmp_s_reg_378.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        exitcond_flatten_reg_348_pp0_iter2_reg = exitcond_flatten_reg_348_pp0_iter1_reg.read();
        tmp_9_reg_373_pp0_iter2_reg = tmp_9_reg_373_pp0_iter1_reg.read();
        tmp_mid2_v_reg_357_pp0_iter2_reg = tmp_mid2_v_reg_357_pp0_iter1_reg.read();
        tmp_s_reg_378_pp0_iter2_reg = tmp_s_reg_378_pp0_iter1_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_1) && esl_seteq<1,1,1>(exitcond_flatten_reg_348_pp0_iter2_reg.read(), ap_const_lv1_0))) {
        p_Val2_7_fu_68 = sum_mult_V_fu_275_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_reg_348_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        r_V_reg_397 = r_V_fu_316_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_fu_155_p2.read(), ap_const_lv1_0))) {
        tmp_2_reg_368 = tmp_2_fu_222_p1.read();
        tmp_9_reg_373 = tmp_9_fu_226_p2.read();
        tmp_s_reg_378 = tmp_s_fu_232_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(exitcond_flatten_fu_155_p2.read(), ap_const_lv1_0))) {
        tmp_mid2_v_reg_357 = tmp_mid2_v_fu_187_p3.read();
    }
}

void matrix_multiply_defa_1::thread_C_0_V_address0() {
    C_0_V_address0 =  (sc_lv<5>) (tmp_mid2_fu_262_p1.read());
}

void matrix_multiply_defa_1::thread_C_0_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_1))) {
        C_0_V_ce0 = ap_const_logic_1;
    } else {
        C_0_V_ce0 = ap_const_logic_0;
    }
}

void matrix_multiply_defa_1::thread_C_0_V_d0() {
    C_0_V_d0 = (!tmp_6_fu_305_p1.read().is_01() || !p_Val2_s_fu_287_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_6_fu_305_p1.read()) + sc_biguint<16>(p_Val2_s_fu_287_p4.read()));
}

void matrix_multiply_defa_1::thread_C_0_V_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(tmp_s_reg_378_pp0_iter2_reg.read(), ap_const_lv1_1))) {
        C_0_V_we0 = ap_const_logic_1;
    } else {
        C_0_V_we0 = ap_const_logic_0;
    }
}

void matrix_multiply_defa_1::thread_Col_assign_mid2_fu_179_p3() {
    Col_assign_mid2_fu_179_p3 = (!exitcond4_fu_173_p2.read()[0].is_01())? sc_lv<3>(): ((exitcond4_fu_173_p2.read()[0].to_bool())? ap_const_lv3_0: Col_assign_reg_144.read());
}

void matrix_multiply_defa_1::thread_F1_V_address0() {
    F1_V_address0 =  (sc_lv<7>) (tmp_3_cast_fu_217_p1.read());
}

void matrix_multiply_defa_1::thread_F1_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1))) {
        F1_V_ce0 = ap_const_logic_1;
    } else {
        F1_V_ce0 = ap_const_logic_0;
    }
}

void matrix_multiply_defa_1::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void matrix_multiply_defa_1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void matrix_multiply_defa_1::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[2];
}

void matrix_multiply_defa_1::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_defa_1::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_defa_1::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_defa_1::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_defa_1::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_defa_1::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_defa_1::thread_ap_block_state5_pp0_stage0_iter3() {
    ap_block_state5_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_multiply_defa_1::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(exitcond_flatten_fu_155_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void matrix_multiply_defa_1::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void matrix_multiply_defa_1::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void matrix_multiply_defa_1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void matrix_multiply_defa_1::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void matrix_multiply_defa_1::thread_ap_phi_mux_Row_assign_phi_fu_137_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_348.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_Row_assign_phi_fu_137_p4 = tmp_mid2_v_reg_357.read();
    } else {
        ap_phi_mux_Row_assign_phi_fu_137_p4 = Row_assign_reg_133.read();
    }
}

void matrix_multiply_defa_1::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void matrix_multiply_defa_1::thread_exitcond4_fu_173_p2() {
    exitcond4_fu_173_p2 = (!Col_assign_reg_144.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(Col_assign_reg_144.read() == ap_const_lv3_4);
}

void matrix_multiply_defa_1::thread_exitcond_flatten_fu_155_p2() {
    exitcond_flatten_fu_155_p2 = (!indvar_flatten_reg_122.read().is_01() || !ap_const_lv7_50.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_122.read() == ap_const_lv7_50);
}

void matrix_multiply_defa_1::thread_indvar_flatten_next_fu_161_p2() {
    indvar_flatten_next_fu_161_p2 = (!indvar_flatten_reg_122.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(indvar_flatten_reg_122.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void matrix_multiply_defa_1::thread_k_2_fu_238_p2() {
    k_2_fu_238_p2 = (!Col_assign_mid2_fu_179_p3.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(Col_assign_mid2_fu_179_p3.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void matrix_multiply_defa_1::thread_p_Val2_8_fu_266_p1() {
    p_Val2_8_fu_266_p1 = esl_sext<35,24>(r_V_reg_397.read());
}

void matrix_multiply_defa_1::thread_p_Val2_9_fu_269_p2() {
    p_Val2_9_fu_269_p2 = (!p_Val2_8_fu_266_p1.read().is_01() || !p_Val2_7_fu_68.read().is_01())? sc_lv<35>(): (sc_bigint<35>(p_Val2_8_fu_266_p1.read()) + sc_biguint<35>(p_Val2_7_fu_68.read()));
}

void matrix_multiply_defa_1::thread_p_Val2_s_fu_287_p4() {
    p_Val2_s_fu_287_p4 = sum_mult_V_fu_275_p3.read().range(23, 8);
}

void matrix_multiply_defa_1::thread_r_V_fu_316_p1() {
    r_V_fu_316_p1 =  (sc_lv<8>) (r_V_fu_316_p10.read());
}

void matrix_multiply_defa_1::thread_r_V_fu_316_p10() {
    r_V_fu_316_p10 = esl_zext<24,8>(F1_V_load_reg_387.read());
}

void matrix_multiply_defa_1::thread_r_fu_167_p2() {
    r_fu_167_p2 = (!ap_const_lv5_1.is_01() || !ap_phi_mux_Row_assign_phi_fu_137_p4.read().is_01())? sc_lv<5>(): (sc_biguint<5>(ap_const_lv5_1) + sc_biguint<5>(ap_phi_mux_Row_assign_phi_fu_137_p4.read()));
}

void matrix_multiply_defa_1::thread_sum_mult_V_fu_275_p3() {
    sum_mult_V_fu_275_p3 = (!tmp_9_reg_373_pp0_iter2_reg.read()[0].is_01())? sc_lv<35>(): ((tmp_9_reg_373_pp0_iter2_reg.read()[0].to_bool())? p_Val2_8_fu_266_p1.read(): p_Val2_9_fu_269_p2.read());
}

void matrix_multiply_defa_1::thread_tmp_2_cast_fu_203_p1() {
    tmp_2_cast_fu_203_p1 = esl_zext<8,7>(tmp_fu_195_p3.read());
}

void matrix_multiply_defa_1::thread_tmp_2_fu_222_p1() {
    tmp_2_fu_222_p1 = Col_assign_mid2_fu_179_p3.read().range(2-1, 0);
}

void matrix_multiply_defa_1::thread_tmp_3_cast_fu_217_p1() {
    tmp_3_cast_fu_217_p1 = esl_zext<64,8>(tmp_3_fu_211_p2.read());
}

void matrix_multiply_defa_1::thread_tmp_3_fu_211_p2() {
    tmp_3_fu_211_p2 = (!tmp_2_cast_fu_203_p1.read().is_01() || !tmp_i_i_cast_fu_207_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_2_cast_fu_203_p1.read()) + sc_biguint<8>(tmp_i_i_cast_fu_207_p1.read()));
}

void matrix_multiply_defa_1::thread_tmp_5_fu_297_p3() {
    tmp_5_fu_297_p3 = sum_mult_V_fu_275_p3.read().range(7, 7);
}

void matrix_multiply_defa_1::thread_tmp_6_fu_305_p1() {
    tmp_6_fu_305_p1 = esl_zext<16,1>(tmp_5_fu_297_p3.read());
}

void matrix_multiply_defa_1::thread_tmp_9_fu_226_p2() {
    tmp_9_fu_226_p2 = (!Col_assign_mid2_fu_179_p3.read().is_01() || !ap_const_lv3_0.is_01())? sc_lv<1>(): sc_lv<1>(Col_assign_mid2_fu_179_p3.read() == ap_const_lv3_0);
}

void matrix_multiply_defa_1::thread_tmp_fu_195_p3() {
    tmp_fu_195_p3 = esl_concat<5,2>(tmp_mid2_v_fu_187_p3.read(), ap_const_lv2_0);
}

void matrix_multiply_defa_1::thread_tmp_i_i_cast_fu_207_p1() {
    tmp_i_i_cast_fu_207_p1 = esl_zext<8,3>(Col_assign_mid2_fu_179_p3.read());
}

void matrix_multiply_defa_1::thread_tmp_mid2_fu_262_p1() {
    tmp_mid2_fu_262_p1 = esl_zext<64,5>(tmp_mid2_v_reg_357_pp0_iter2_reg.read());
}

void matrix_multiply_defa_1::thread_tmp_mid2_v_fu_187_p3() {
    tmp_mid2_v_fu_187_p3 = (!exitcond4_fu_173_p2.read()[0].is_01())? sc_lv<5>(): ((exitcond4_fu_173_p2.read()[0].to_bool())? r_fu_167_p2.read(): ap_phi_mux_Row_assign_phi_fu_137_p4.read());
}

void matrix_multiply_defa_1::thread_tmp_s_fu_232_p2() {
    tmp_s_fu_232_p2 = (!Col_assign_mid2_fu_179_p3.read().is_01() || !ap_const_lv3_3.is_01())? sc_lv<1>(): sc_lv<1>(Col_assign_mid2_fu_179_p3.read() == ap_const_lv3_3);
}

void matrix_multiply_defa_1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(exitcond_flatten_fu_155_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) && !(esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) || (esl_seteq<1,1,1>(exitcond_flatten_fu_155_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

